"""
Settings for nba_fantasy_analyzer project.
"""
from pathlib import Path
import decouple

BASE_DIR = Path(__file__).resolve().parent.parent

config = decouple.AutoConfig(BASE_DIR)


MONGO_DATABASE_URL = config("MONGO_DATABASE_URL")
MONGODB_NAME = config("MONGO_DATABASE")
MY_TEAM_DATA_COLLECTION = config("MY_TEAM_DATA")
ALL_TEAMS_DAILY_DATA_COLLECTION = config("ALL_TEAMS_DAILY_DATA")
ALL_TEAMS_WEEKLY_DATA_COLLECTION = config("ALL_TEAMS_WEEKLY_DATA")
PLAYERS_DATA_ESPN_COLLECTION = config("PLAYERS_DATA_ESPN")
PLAYERS_DATA_API_COLLECTION = config("PLAYERS_DATA_API_COLLECTION")
PLAYERS_HISTORICAL_DATA_COLLECTION = config("PLAYERS_HISTORICAL_DATA_COLLECTION")
MATCHUP_PREDICTION_ESPN_COLLECTION = config("MATCHUP_PREDICTION_ESPN_COLLECTION")
MATCHUP_PREDICTION_API_COLLECTION = config("MATCHUP_PREDICTION_API_COLLECTION")

NBA_API_KEY = config("NBA_API_KEY")
NBA_API_DAILY_LIMIT = config("NBA_API_DAILY_LIMIT")
NBA_FANTASY_LEAGUE_ID = config("NBA_FANTASY_LEAGUE_ID")
NBA_FANTASY_SEASON_ID = config("NBA_FANTASY_SEASON_ID")
NBA_FANTASY_ESPNS2 = config("NBA_FANTASY_ESPNS2")
NBA_FANTASY_SWID = config("NBA_FANTASY_SWID")
NBA_FANTASY_MY_TEAM = config("NBA_FANTASY_MY_TEAM")
