version: "3.7"

services:

  mongodb:
    image: mongo:5.0.5
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env

#  web:
#     build:
#       context: .
#       target: backend
#     image: nba_fantasy_analyzer
#     env_file:
#       - .env
#     volumes:
#       - .:/app
#     stdin_open: true
#     tty: true
#     depends_on:
#       - mongodb
