
from nba_fantasy_analyzer.settings import config


MONGO_DATABASE_URL = config("MONGO_DATABASE_URL")
MONGODB_NAME = config("MONGO_DATABASE")
MY_TEAM_DATA_COLLECTION = config("MY_TEAM_DATA")
ALL_TEAMS_DAILY_DATA_COLLECTION = config("ALL_TEAMS_DAILY_DATA")
ALL_TEAMS_WEEKLY_DATA_COLLECTION = config("ALL_TEAMS_WEEKLY_DATA")
PLAYERS_DATA_ESPN_COLLECTION = config("PLAYERS_DATA_ESPN")
PLAYERS_DATA_API_COLLECTION = config("PLAYERS_DATA_API_COLLECTION")
PLAYERS_HISTORICAL_DATA_COLLECTION = config("PLAYERS_HISTORICAL_DATA_COLLECTION")
MATCHUP_PREDICTION_ESPN_COLLECTION = config("MATCHUP_PREDICTION_ESPN_COLLECTION")
MATCHUP_PREDICTION_API_COLLECTION = config("MATCHUP_PREDICTION_API_COLLECTION")

